### PR TITLE
Create disable_mayhem_modifiers.txt

### PR DESCRIPTION
**Pull request by aelicante**
Add mod to disable all Mayhem 2 modifiers. Do not touch health, shield and armor scaling.

### CODE REVIEW

**Comment by aelicante** [comment]
I enjoy the added difficulty of Mayhem 2, but I feel modifiers can be distracting. Inspired by your mods to disable specific modifiers this one will disable all possible modifiers. Scaling is otherwise untouched and it should be compatible with all other scaling mods.

**Comment by apocalyptech** [comment]
Oh, y'know, I realize now that I never actually responded to this, sorry!

So I've been sort of trying to figure out how to handle actual mod dispersal on here -- in the end, on my own repo, I'd probably only want to be hosting my own mods, so I'm somewhat unlikely to merge this in.  I've been considering forking off the mods to their own repo (separate from the hotfix injection thing) as well, but the question remains that as more folks start modding, what's the best way for people to *find* mods?

A few of us have been talking about maybe creating another "group" github like the one that's been used for BL2/TPS in the past, something like https://github.com/BLCM/BLCMods/ - That would also let us do stuff like create a ModCabinet-like wiki for finding mods as well, a la https://github.com/BLCM/ModCabinet/wiki

The main question is if we should maybe move away from github entirely, though -- for more inexperienced users, there's a lot of barriers to entry for managing git content, even with user-oriented apps like Github Desktop to fall back on. That said, if it's not github, where the heck would it be?  I'm not personally very fond of Nexus, and I definitly won't be bothering to put my own mods up there  But having *some* kind of centralized place for these might be nice.

Anyway, I'll keep this PR open, even though as I said I'm probably unlikely to actually merge it in, but I would like to figure out a centralized repository of some sort, so that BL3 mods like this could be more easily findable.  I'll let you know if I come up with anything, and if you've got ideas of your own, please let me know.  :+1: 

Thanks for the PR, of course!  I'm always glad to see more folks modding the game.

**Comment by aelicante** [comment]
I understand. Considering it's still the infancy of BL3 modding - and that I'm unlikely to have enough mods of my own to host them separately I thought it would be easier.

Source control bring a lot to the table in terms of ease of update and management that would otherwise be a pain in Nexus, or require additional development for an ad-hoc solution. The github group sounds like a good idea but doesn't negate the barrier of entry. Likewise, I don't see any silver bullet solution.

**Comment by apocalyptech** [comment]
Heh, yeah, git really hits the sweet spot of both functionality, and also not being tied in to any particular service provider.  If github ever gets awful, it's trivial enough to just clone the repo on any other hosted solution, etc  I'm definitely super fond of it, personally, but I know from experience that less conversant folks trying to get mods into the system are often super confused by things.  There's definitely a few areas that I wish github.com did a slightly better job of handholding, for git newbies.

Anyway, I dunno, perhaps I will just get that group github going this weekend yet  I'll let you know in here.  :)

**Comment by apocalyptech** [comment]
Okay!  So, a productive few days working on bl3 modding infrastructure.  I'm going to close out this PR without merging, since my own mods no longer live in this repo.  Rather, they now live here:

https://github.com/BLCM/bl3mods

Feel free to submit a PR for that repo -- create a new directory for your user and do it that way.  This repo has an associated wiki that gets auto-built, which you can see here:

https://github.com/BLCM/BL3ModCabinet/wiki

If you'd like your mod to be included in that wiki, make sure you follow the guidelines: https://github.com/BLCM/BL3ModCabinet/wiki/Contributing-to-BL3-ModCabinet

The most important bits are that the mod will have to have a `.bl3hotfix` extension, and have a `Name:` and `Categories:` bit in the comments up at the top of the mod file.

Thx, enjoy!

**Comment by aelicante** [comment]
Thanks for letting me know, I'll check that.

**Pull request closed without merging**
